---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kb.crd.dango.io
  resources:
  - websites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kb.crd.dango.io
  resources:
  - websites/finalizers
  verbs:
  - update
- apiGroups:
  - kb.crd.dango.io
  resources:
  - websites/status
  verbs:
  - get
  - patch
  - update
